resolver: lts-13.1
packages:
- discrimination-ieee754
- lens-labels
- proto-lens
- proto-lens-arbitrary
- proto-lens-discrimination
- proto-lens-optparse
- proto-lens-protobuf-types
- proto-lens-protoc
- proto-lens-runtime
- proto-lens-setup
# Internal packages, not to be released:
- proto-lens-benchmarks
- proto-lens-tests
- proto-lens-tests-dep
extra-deps:
- git: https://github.com/ekmett/discrimination
  commit: 866f92068cb2e2fe1a0753ad2983641951796b8a
- promises-0.3

ghc-options:
  "$locals": -Wall -Werror
